[package]
name = "multi-party-ecdsa"
version = "0.2.2"
authors = [
    "Gary <gary@kzencorp.com>",
    "Omer <omer.shlomovits@gmail.com>"
]
keywords = [
    "ecdsa",
    "multi-party-ecdsa",
    "signature",
    "rust",
    "secret-shares",
    "blockchain",
    "cryptography",
    "cryptocurrency"]

homepage = "https://github.com/KZen-networks/multi-party-ecdsa"
repository = "https://github.com/KZen-networks/multi-party-ecdsa"
license = "GPL-3.0-or-later"
categories = ["cryptography"]

[lib]
crate-type = ["lib"]


[dependencies]
paillier = { git = "https://github.com/boazarad88/rust-paillier" }
zk-paillier = { git = "https://github.com/boazarad88/zk-paillier" }
subtle = {version = "2", features = ["nightly"]}
serde = "1.0"
serde_derive = "1.0"


[features]
cclst = ["class_group"]

[dependencies.curv]
git = "https://github.com/boazarad88/curv"
tag = "v0.2.2"
features =  ["ec_secp256k1"]

[dependencies.centipede]
git = "https://github.com/boazarad88/centipede"
# tag = "v0.2.0"

[dependencies.class_group]
git = "https://github.com/KZen-networks/class-groups"
tag = "v0.1.4"
optional = true

[dependencies.rocket]
version = "0.4.2"
default-features = false
optional = true



[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }

[dev-dependencies]
criterion = "0.2"
hex = "0.3.2"
rocket_contrib = {version = "0.4.2",default-features = false,features = ["json"]}
rocket = {version = "0.4.2", default-features = false}
reqwest = {version = "0.9.5", default-features = false}
uuid = { version = "0.7", features = ["v4"] }
rust-crypto = "^0.2"
serde_json = "1.0"

[[example]]
name = "sm_manager"

[[example]]
name = "gg18_keygen_client"

[[example]]
name = "gg18_sign_client"

[[bench]]
name = "keygen"
path = "benches/two_party_ecdsa/cclst_2019/keygen.rs"
harness = false
